# This file is automatically generated. Please do not modify.

from . import AsciiArt

adélie = AsciiArt(match=r'''"Adélie"* | "Adelie"*''', color='4 7 6', ascii=r"""
${c1}                 ${c3} ,-^-___
${c3}                /\\\///
${c2}refined.${c1}       /\\\\//
${c2}reliable.${c1}     /\\\///
${c2}ready.${c1}       /\\/////\
        __///\\\\/////\
${c3}     _//////\\\\\\\////
${c1}   ///////${c3}\\\\\\\\\\//
          //////${c1}\\\\\/
          /////\\\\\/
          /////${c3}\\\\/
         /\\///\\\/
         /\\\/${c1}\\/
         /\\\\//
        //////
      /// ${c3}\\\\\
""")
    