# This file is automatically generated. Please do not modify.

from . import AsciiArt

digital_unix = AsciiArt(match=r'''"digital UNIX"*''', color='1 6 7', ascii=r"""
${c1}     +-+-+-+-+-+-+-+
     |${c3}d${c1}|${c3}i${c1}|${c3}g${c1}|${c3}i${c1}|${c3}t${c1}|${c3}a${c1}|${c3}l${c1}|
     +-+-+-+-+-+-+-+
${c2} _    _ _   _ _______   __
| |  | | \ | |_   _\ \ / /
| |  | |  \| | | |  \ V /
| |  | | . ` | | |   > <
| |__| | |\  |_| |_ / . \
 \____/|_| \_|_____/_/ \_\
""")
    