# This file is automatically generated. Please do not modify.

from . import AsciiArt

fedora_kinoite = AsciiArt(match=r'''"Fedora Kinoite"* | "Kinoite"*''', color='12 7', ascii=r"""
${c1} ,clll:.${c2}          .,::::::::::::'
${c1}:ooooooo${c2}        .;::::::::::::::
${c1}looooooo${c2}       ,:::::::::::::::'
${c1}looooooo${c2}      .::::::::::::::::
${c1}looooooo${c2}      ;:::::::::::::::.
${c1}looooooo${c2}     .::::::::::::::::
${c1}looooool${c2};;;;,::::::::::::::::
${c1}looool${c2}::,   .::::::::::::::
${c1}looooc${c2}::     ;::
${c1}looooc${c2}::;.  .::;
${c1}loooool${c2}:::::::::::.
${c1}looooooo${c2}.    .::::::'
${c1}looooooo${c2}       .::::::,;,..
${c1}looooooo${c2}          :::;' ';:;.
${c1}looooooo${c2}          :::     :::
${c1}cooooooo${c2}          .::'   '::.
 ${c1}.ooooc ${c2}            ::, ,::
                      ''''
""")
    