# This file is automatically generated. Please do not modify.

from . import AsciiArt

linux_small = AsciiArt(match=r'''"Linux_small"''', color='fg 8 3', ascii=r"""
${c2}    ___
${c2}   (${c1}.. ${c2}|
${c2}   (${c3}<> ${c2}|
${c2}  / ${c1}__  ${c2}\
${c2} ( ${c1}/  \ ${c2}/|
${c3}_${c2}/\ ${c1}__)${c2}/${c3}_${c2})
${c3}\/${c2}-____${c3}\/
""")
    