# This file is automatically generated. Please do not modify.

from . import AsciiArt

meowix = AsciiArt(match=r'''"Meowix"*''', color='1 3 3 4', ascii=r"""
${c1}         #${c2}%            ${c3}&${c4}*
${c1}        ##${c2}%%          ${c3}&&${c4}**
${c1}       ##  ${c2}%%        ${c3}&&  ${c4}**
${c1}      ##    ${c2}%%      ${c3}&&    ${c4}**
${c1}     ##      ${c2}%%    ${c3}&&      ${c4}**
${c1}    ##        ${c2}%%  ${c3}&&        ${c4}**
${c1}   ##          ${c2}%%${c3}&&          ${c4}**
${c1}  ##            ${c2}%%            ${c4}**
${c1} ##                            ${c4}**
${c1}##                              ${c4}**
""")
    