# This file is automatically generated. Please do not modify.

from . import AsciiArt

peropesis = AsciiArt(match=r'''"Peropesis"*''', color='4 7 1', ascii=r"""
${c1}####  #### ####   ###   ####  ####  #### #  ####
#   # #    #   # #   #  #   # #     #    #  #
####  ###  #### #     # ####  ###     #  #    #
#     #    #  #  #   #  #     #        # #     #
#     #### #   #  ###   #     #### ####  # ####
""")
    