# This file is automatically generated. Please do not modify.

from . import AsciiArt

pikaos = AsciiArt(match=r'''"PikaOS"*''', color='11', ascii=r"""
${c1}
                  '',,,               ,,,d,
              ',,                           ,,'
           ',                                   ,.
         .,                                       '
        .                                           .
      '                                               .
    ..                   oddddkdlc:;,..                ..
   .                        ............lllc,            .
  .                       ....................:           .
 .                        .  ....................
      '.                     ..........'o........d0XX0.
     ....lllllllcOOOcllllll............cxlxc...;okkkx.
     ..................................';lc'...lo.
    .'''''''''''''.....................,;,.......
    ',,,,,,,,,,,,,,,,''...............dkkkd......
    ',,,,,,,,,,,,,,,,,,,'............;okkkd;....
    .,,,,,,,,,,,,,,,,,,,,,............;cll;.....
      ,,,,,,,,,,,,,,,,,,,,'....................:d,
       ,,,,,,,,,,,,,,,,,,,....................oxxx:
        .,,,,,,,,,,,,,,,,,'..................oxxxxx.  .
         .,,,,,,,,,,,,,,'..........        ,oxxxxxxx .
        .;,,,,,,,,,,,,'..                'cxxxxxxxxx,
         :dl:,'',,'....               .;lxxxxxxxxxd;
          ,codol:;'.           ...,;cldxxxxxxxxxoc.
            .:cxxxxxdlccccc:ccldxxxxxxxxxxxxxx::.
              .'::dxxxxxxxxxxxxxxxxxxxxxxxd::'.
                 ..,::cdxxxxxxxxxxxxxdc::,..
                      ...,;:::::::;,...
""")
    