# This file is automatically generated. Please do not modify.

from . import AsciiArt

tatra = AsciiArt(match=r'''"Tatra"*''', color='4 7', ascii=r"""
${c1}
         . .:. .         .:.
        .^^.!.:::.    .^!?J?^
      .:^.^!!!~:~^.  .7??77!~~^.
     .~^.!??77?!.^~:  ..:^^7JJJ7~~^.
     .^~.^7???7~.~~.   .7??????????!
      .:^:^^~^^:!^ ^:  .......^!:...
    .!7~.::.!.::. ~BG~    :^  ^~:
    :!!~   ~.    ?BBBB!  ^?J!.  .!~.
     :!. .JBY. .Y#BBBY?~!???J7. :^^.
     .. :5#B#P~P#BBP?7?55J?J7:
       ^P#BBBBBBBB5?7J5555J!.....
      !BBBBBBGBBGJ77::Y555J?77777^
     ?BBBBG5JJ5PJ?!:  .?Y??????77?~.
   .YBGPYJ??????Y?^^^^~7?????????7?!.
   .^^:..::::::::.....:::::::::::..:.
""")
    