# This file is automatically generated. Please do not modify.

from . import AsciiArt

venom_small = AsciiArt(match=r'''"venom_small"*''', color='8 4', ascii=r"""
${c1} ++**
  *===**====+*
   *====*   +===+
 *==*+===*    *===*
*===* *===+    *===*
*===*  +===+   *===*
*===*   +===*  *===*
 *===*    *===+*==*
   +===+   *===+=*
      *+====**===*
               **++
""")
    